apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.volumes.storage . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.volumes.storage_size | quote }}
