apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage_volume | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage_volume_size | quote }}
